import { startRecording } from "./recorder.js";

const info = document.getElementById("info");
const textArea = document.getElementById("text");
const synthBtn = document.getElementById("synthesize");
const player = document.getElementById("player");
const languageSelect = document.getElementById("language");
const voiceSelect = document.getElementById("voice");
const temperatureSlider = document.getElementById("temperature");
const temperatureValue = document.getElementById("temperature-value");
const progressWrap = document.getElementById("progress-wrap");
const progressLabel = document.getElementById("progress-label");
const progressFill = document.getElementById("progress-fill");
const checkpointInput = document.getElementById("checkpoint");
const cloneInput = document.getElementById("clone-wav");
const cloneHint = document.getElementById("clone-hint");
const recordBtn = document.getElementById("record-voice");
const recordPanel = document.getElementById("record-panel");
const recordScript = document.getElementById("record-script");
const recordMeter = document.getElementById("record-meter");
const recordLevel = document.getElementById("record-level");
const recordTimer = document.getElementById("record-timer");
const recordPreview = document.getElementById("record-preview");
const recordStartBtn = document.getElementById("record-start");
const recordStopBtn = document.getElementById("record-stop");
const recordCloneBtn = document.getElementById("record-clone");
const recordRetakeBtn = document.getElementById("record-retake");
const recordDiscardBtn = document.getElementById("record-discard");
const recordDownload = document.getElementById("record-download");

// languages.json is generated by `go generate ./internal/webmanifest/`: every
// embedded model config with its Hugging Face URLs at pinned revisions.
const catalogAssetPath = "./languages.json";
const kernelAssetPath = "./pockettts-kernel.wasm";

// The kernel clones from the first 30 s of a prompt, so a recording stops
// there; shorter than recordShortSeconds earns a warning.
const recordMaxSeconds = 30;
const recordShortSeconds = 5;

// readingScripts are passages to read aloud for a voice prompt: a pangram,
// plain narration, a question and an exclamation cover a natural range of
// sounds and intonation.
const readingScripts = {
  english:
    "The quick brown fox jumps over the lazy dog. On a bright Sunday morning, I walked along the river and " +
    "watched the boats drift slowly by. A cup of hot tea, a good book and a quiet garden are all I need to relax. " +
    "Could you please call me back tomorrow at about half past nine? Thank you, and have a wonderful day!",
  german:
    "Franz jagt im komplett verwahrlosten Taxi quer durch Bayern. An einem sonnigen Sonntagmorgen bin ich am " +
    "Fluss entlanggegangen und habe den Booten zugesehen. Eine Tasse heißer Tee, ein gutes Buch und ein ruhiger " +
    "Garten – mehr brauche ich nicht zum Entspannen. Könnten Sie mich bitte morgen gegen halb zehn zurückrufen? " +
    "Vielen Dank und einen schönen Tag noch!",
};

const state = {
  kernelReady: false,
  kernelStopped: false,
  kernelVersion: "",
  kernelReadyPromise: null,
  // Kernel loads and unloads run one at a time, in the order they were asked.
  kernelChain: Promise.resolve(),
  catalog: null,
  // config is the selected model config; loadedConfig the one in the kernel.
  config: "",
  loadedConfig: "",
  loadSeq: 0,
  loadAbort: null,
  modelPhase: "idle",
  modelError: "",
  // checkpointName is the local file the selected config loads from; "" means
  // the ungated checkpoint on Hugging Face.
  checkpointName: "",
  // canClone is the kernel's verdict on the loaded checkpoint: only the gated
  // kyutai/pocket-tts weights have a voice encoder.
  canClone: false,
  isCloning: false,
  isSynthesizing: false,
  textDirty: false,
  activeAudioURL: "",
  // Voice caches are keyed by config and voice ID: configs reuse voice IDs
  // with different files.
  voiceBytes: new Map(),
  voiceDownloads: new Map(),
  voiceErrors: new Map(),
  // clonedVoices maps a config to the IDs of the voices cloned for it; their
  // bytes are in voiceBytes like downloaded ones.
  clonedVoices: new Map(),
  // recordPhase is the step of the microphone panel: "closed", "ready" (the
  // script is shown), "starting" (waiting for the microphone), "recording",
  // "stopping" (collecting the last audio) or "recorded" (a take awaits cloning).
  recordPhase: "closed",
  // recorder is the running capture from startRecording, null when none runs.
  recorder: null,
  // recording is the last take: its WAV bytes, an object URL for preview and
  // download, and its length in seconds; null when there is none.
  recording: null,
  // recordSeq supersedes a pending start or stop when the panel closes or the
  // model switches.
  recordSeq: 0,
  // recordingCount numbers the voices cloned from recordings (clone-recording-N).
  recordingCount: 0,
  // textEdited is set once the user types; their text then survives a switch
  // (unless they empty the box), even if it equals a demo text.
  textEdited: false,
  action: "Starting...",
};

function formatError(err) {
  if (!err) return "unknown error";
  if (typeof err === "string") return err;
  if (err.message) return err.message;
  try {
    return JSON.stringify(err);
  } catch (_) {
    return String(err);
  }
}

function decodeBase64ToBytes(base64) {
  const bin = atob(base64);
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i += 1) {
    bytes[i] = bin.charCodeAt(i);
  }
  return bytes;
}

function setAudioBlob(wavBytes) {
  if (state.activeAudioURL) {
    URL.revokeObjectURL(state.activeAudioURL);
  }

  const blob = new Blob([wavBytes], { type: "audio/wav" });
  const url = URL.createObjectURL(blob);
  state.activeAudioURL = url;
  player.src = url;
  player.style.display = "";
}

function voiceKey(config, voiceID) {
  return `${config}/${voiceID}`;
}

function selectedVoiceID() {
  return String(voiceSelect.value || "");
}

function selectedVoiceKey() {
  const voiceID = selectedVoiceID();
  return voiceID ? voiceKey(state.config, voiceID) : "";
}

function findVoice(config, voiceID) {
  const lang = (state.catalog?.languages || []).find((l) => l.name === config);
  return (lang?.voices || []).find((v) => v.id === voiceID) || null;
}

function clonedVoiceIDs(config) {
  return state.clonedVoices.get(config) || [];
}

// dropClonedVoices forgets every cloned voice: a clone is the output of the
// loaded checkpoint's voice encoder and speaker projection, so it must not
// reach a model loaded from another checkpoint.
function dropClonedVoices() {
  for (const [config, ids] of state.clonedVoices) {
    for (const id of ids) {
      state.voiceBytes.delete(voiceKey(config, id));
      state.voiceErrors.delete(voiceKey(config, id));
    }
  }
  state.clonedVoices.clear();
}

function selectedVoiceState() {
  const key = selectedVoiceKey();
  if (!key) return "unavailable";
  if (state.voiceBytes.has(key)) return "ready";
  if (state.voiceDownloads.has(key)) return "downloading";
  if (state.voiceErrors.has(key)) return "error";
  if (findVoice(state.config, selectedVoiceID())) return "missing";
  return "unavailable";
}

function modelReady() {
  return state.modelPhase === "ready" && state.loadedConfig === state.config;
}

function modelSourceText() {
  return state.checkpointName ? `local ${state.checkpointName}` : "Hugging Face, ungated";
}

function modelStatusText() {
  const name = state.config || "none";
  if (modelReady()) return `${name} ready (${modelSourceText()})`;
  if (state.modelPhase === "downloading") return `${name} downloading`;
  if (state.modelPhase === "initializing") return `${name} initializing`;
  if (state.modelPhase === "error") return `${name} error (${state.modelError})`;
  return `${name} idle`;
}

function voiceStatusText() {
  const voiceID = selectedVoiceID();
  const voiceState = selectedVoiceState();

  if (!voiceID) return "unavailable";
  if (voiceState === "ready") return `${voiceID} ready`;
  if (voiceState === "downloading") return `${voiceID} downloading`;
  if (voiceState === "missing") return `${voiceID} not downloaded`;
  if (voiceState === "error") return `${voiceID} error (${state.voiceErrors.get(selectedVoiceKey())})`;
  return `${voiceID} unavailable`;
}

function isRecording() {
  return state.recordPhase === "recording" || state.recordPhase === "stopping";
}

// microphoneBusy also covers the wait for microphone permission.
function microphoneBusy() {
  return state.recordPhase === "starting" || isRecording();
}

function cloneStatusText() {
  if (!modelReady()) return "waiting for the model";
  if (isRecording()) return "recording";
  if (state.isCloning) return "cloning";
  if (state.canClone) return "available";
  return "unavailable (ungated checkpoint)";
}

// gatedCheckpointHint names the file of the selected config in the gated
// kyutai/pocket-tts repo, derived from its ungated download URL.
function gatedCheckpointHint() {
  const lang = (state.catalog?.languages || []).find((l) => l.name === state.config);
  const match = /\/kyutai\/pocket-tts-without-voice-cloning\/resolve\/[^/]+\/(.+)$/.exec(lang?.model || "");
  return match ? `${match[1]} from https://huggingface.co/kyutai/pocket-tts` : "the checkpoint from kyutai/pocket-tts";
}

function renderCloneHint() {
  if (!modelReady()) {
    cloneHint.textContent = "";
  } else if (state.canClone) {
    cloneHint.textContent = "Voice cloning available: pick a WAV prompt or record one (the first 30 s are used).";
  } else {
    const loaded = state.checkpointName || "the ungated Hugging Face checkpoint";
    cloneHint.textContent =
      `Voice cloning unavailable: ${loaded} has zeroed voice encoder weights. ` +
      `Accept the terms of the gated kyutai/pocket-tts repo on Hugging Face, download ${gatedCheckpointHint()} ` +
      `and pick it with "Use local checkpoint".`;
  }
}

function renderInfo() {
  const lines = [
    `Kernel: ${state.kernelReady ? `ready (${state.kernelVersion})` : "not ready"}`,
    `Model: ${modelStatusText()}`,
    `Voice: ${voiceStatusText()}`,
    `Cloning: ${cloneStatusText()}`,
    `State: ${state.action}`,
  ];
  info.textContent = lines.join("\n");
  renderCloneHint();
}

function setAction(message) {
  state.action = message;
  renderInfo();
}

function showProgress(label, pct, done) {
  progressWrap.classList.add("visible");
  progressLabel.textContent = label;
  progressFill.style.width = `${Math.min(100, Math.max(0, pct))}%`;
  progressFill.classList.toggle("done", !!done);
}

function hideProgress() {
  progressWrap.classList.remove("visible");
}

const btnLabel = document.getElementById("btn-label");

function canSynthesize() {
  // The microphone would pick up the playback, and the kernel would stall the
  // page while it records.
  if (microphoneBusy()) return false;
  const baseReady = state.kernelReady && modelReady() && selectedVoiceState() === "ready";
  // Allow clicking again if the user edited the text while a synthesis is running.
  return baseReady && (!state.isSynthesizing || state.textDirty);
}

function setSynthesizeEnabled() {
  const enabled = canSynthesize();
  const showSpinner = state.isSynthesizing && !state.textDirty;
  synthBtn.disabled = !enabled;
  synthBtn.classList.toggle("ready", enabled && !showSpinner);
  synthBtn.classList.toggle("synthesizing", showSpinner);
  btnLabel.textContent = showSpinner ? "Synthesizing…" : "Synthesize";
  // A synthesis runs on the loaded model; switching it away mid-run is not
  // supported, and a stopped kernel loads nothing.
  const busy = state.isSynthesizing || state.isCloning || microphoneBusy();
  languageSelect.disabled = busy || !state.catalog || state.kernelStopped;
  checkpointInput.disabled = busy || !state.catalog || state.kernelStopped;
  cloneInput.disabled = busy || !state.kernelReady || !modelReady() || !state.canClone;
  recordBtn.disabled = busy || !state.kernelReady || !modelReady() || !state.canClone;
  renderRecordPanel();
}

function formatSeconds(seconds) {
  const s = Math.floor(seconds);
  return `${Math.floor(s / 60)}:${String(s % 60).padStart(2, "0")}`;
}

// setRecordMeter shows the elapsed time and the RMS level (0..1) mapped from
// -60..0 dBFS onto the bar.
function setRecordMeter(seconds, level) {
  const db = 20 * Math.log10(Math.max(level, 1e-6));
  const pct = Math.min(100, Math.max(0, ((db + 60) / 60) * 100));
  recordLevel.style.width = `${pct}%`;
  recordTimer.textContent = `${formatSeconds(seconds)} / ${formatSeconds(recordMaxSeconds)}`;
}

function readingScript(config) {
  return String(config || "").startsWith("german") ? readingScripts.german : readingScripts.english;
}

// renderRecordPanel shows the controls of the current recording step. Starting
// a take and cloning one need the same model state as cloning from a file.
function renderRecordPanel() {
  const phase = state.recordPhase;
  const recorded = phase === "recorded" && !!state.recording;
  const idle = modelReady() && state.canClone && !state.isCloning && !state.isSynthesizing;

  recordPanel.hidden = phase === "closed";
  recordPanel.classList.toggle("live", phase === "recording");
  recordMeter.hidden = recorded;

  recordStartBtn.hidden = phase !== "ready" && phase !== "starting";
  recordStartBtn.disabled = phase === "starting" || !idle;
  recordStopBtn.hidden = !isRecording();
  recordStopBtn.disabled = phase === "stopping";
  recordStopBtn.classList.toggle("live", phase === "recording");
  recordCloneBtn.hidden = !recorded;
  recordCloneBtn.disabled = !idle;
  recordRetakeBtn.hidden = !recorded;
  recordRetakeBtn.disabled = !idle;
  recordDiscardBtn.textContent = phase === "ready" ? "Close" : "Discard";
  recordDiscardBtn.disabled = phase === "stopping";

  // Only touch the media source when it changes: reassigning it would reset
  // the player.
  const url = recorded ? state.recording.url : "";
  if ((recordPreview.getAttribute("src") || "") !== url) {
    recordPreview.pause();
    if (url) {
      recordPreview.src = url;
    } else {
      recordPreview.removeAttribute("src");
      recordPreview.load();
    }
  }
  recordPreview.hidden = !recorded;
  if (url) {
    recordDownload.href = url;
  } else {
    recordDownload.removeAttribute("href");
  }
  recordDownload.hidden = !recorded;
}

async function fetchBytesWithProgress(url, onProgress, signal) {
  const res = await fetch(url, { signal });
  if (!res.ok) {
    throw new Error(`fetch ${url} failed (${res.status})`);
  }

  const contentLength = parseInt(res.headers.get("content-length") || "0", 10);
  if (!res.body) {
    const buf = await res.arrayBuffer();
    if (onProgress) onProgress(buf.byteLength, buf.byteLength);
    return new Uint8Array(buf);
  }

  const reader = res.body.getReader();
  const chunks = [];
  let received = 0;

  for (;;) {
    const { done, value } = await reader.read();
    if (done) break;
    chunks.push(value);
    received += value.length;
    if (onProgress) onProgress(received, contentLength);
  }

  const out = new Uint8Array(received);
  let offset = 0;
  for (const chunk of chunks) {
    out.set(chunk, offset);
    offset += chunk.length;
  }
  if (onProgress) onProgress(received, contentLength || received);
  return out;
}

async function bootKernel() {
  const go = new Go();
  const wasm = await WebAssembly.instantiateStreaming(fetch(kernelAssetPath), go.importObject);
  // The kernel never returns on its own; it exits on a fatal error such as
  // running out of WASM memory, after which every call fails.
  go.run(wasm.instance).then(() => {
    state.kernelReady = false;
    state.kernelStopped = true;
    state.modelPhase = "error";
    state.modelError = "kernel stopped";
    hideProgress();
    setAction("The WASM kernel stopped (likely out of memory); reload the page.");
    setSynthesizeEnabled();
  });

  const kernel = globalThis.PocketTTSKernel;
  if (!kernel) {
    throw new Error("PocketTTSKernel not found after wasm startup");
  }
  for (const fn of ["synthesize", "loadModel", "unloadModel", "cloneVoice"]) {
    if (typeof kernel[fn] !== "function") {
      throw new Error(`PocketTTSKernel.${fn} is missing`);
    }
  }

  state.kernelReady = true;
  state.kernelVersion = String(kernel.version || "unknown");
  renderInfo();
  setSynthesizeEnabled();
}

// enqueueKernel runs task after every kernel task queued before it.
function enqueueKernel(task) {
  const run = state.kernelChain.then(task);
  state.kernelChain = run.catch(() => {});
  return run;
}

function languageLabel(lang) {
  const large = lang.layers > 6 ? ", large download" : "";
  return `${lang.name} (${lang.layers} layers${large})`;
}

function populateLanguageDropdown() {
  languageSelect.innerHTML = "";

  for (const lang of state.catalog.languages) {
    const opt = document.createElement("option");
    opt.value = lang.name;
    opt.textContent = languageLabel(lang);
    languageSelect.appendChild(opt);
  }
}

function populateVoiceDropdown(lang) {
  const voices = lang?.voices || [];
  voiceSelect.innerHTML = "";

  for (const v of voices) {
    const opt = document.createElement("option");
    opt.value = v.id;
    opt.textContent = v.id;
    voiceSelect.appendChild(opt);
  }

  for (const id of clonedVoiceIDs(lang?.name)) {
    const opt = document.createElement("option");
    opt.value = id;
    opt.textContent = `${id} (cloned)`;
    voiceSelect.appendChild(opt);
  }

  if (voices.some((v) => v.id === lang.default_voice)) {
    voiceSelect.value = lang.default_voice;
  } else if (voices.length > 0) {
    voiceSelect.value = voices[0].id;
  }
}

function setTemperature(val) {
  temperatureSlider.value = String(val);
  temperatureValue.textContent = Number(val).toFixed(2);
}

// applyLanguageDefaults selects the config's default voice and temperature,
// and its default text unless the user has typed their own.
function applyLanguageDefaults(lang) {
  populateVoiceDropdown(lang);
  setTemperature(lang.default_temperature);

  if (!state.textEdited || textArea.value.trim() === "") {
    textArea.value = lang.default_text;
    state.textEdited = false;
  }
}

// ensureVoiceDownloaded fetches a voice once; signal aborts the download
// (a model switch aborts the previous config's downloads).
async function ensureVoiceDownloaded(config, voiceID, signal) {
  if (!voiceID) return null;

  const key = voiceKey(config, voiceID);

  if (state.voiceBytes.has(key)) {
    return state.voiceBytes.get(key);
  }

  if (state.voiceDownloads.has(key)) {
    return state.voiceDownloads.get(key);
  }

  const voice = findVoice(config, voiceID);
  if (!voice) {
    const msg = `voice ${voiceID} is not a ${config} voice`;
    state.voiceErrors.set(key, msg);
    throw new Error(msg);
  }

  state.voiceErrors.delete(key);

  let lastPct = -1;
  const promise = (async () => {
    const bytes = await fetchBytesWithProgress(voice.url, (received, total) => {
      const pct = total > 0 ? Math.min(100, Math.round((received / total) * 100)) : 0;
      if (pct !== lastPct && pct % 10 === 0 && selectedVoiceKey() === key) {
        lastPct = pct;
        setAction(`Downloading voice ${voiceID} (${pct}%)...`);
      }
    }, signal);
    state.voiceBytes.set(key, bytes);
    return bytes;
  })();

  state.voiceDownloads.set(key, promise);
  renderInfo();
  setSynthesizeEnabled();

  try {
    const bytes = await promise;
    return bytes;
  } catch (err) {
    // An aborted download is retried the next time the voice is needed.
    if (err?.name !== "AbortError") state.voiceErrors.set(key, formatError(err));
    throw err;
  } finally {
    state.voiceDownloads.delete(key);
    renderInfo();
    setSynthesizeEnabled();
  }
}

async function downloadSelectedVoiceIfNeeded() {
  const config = state.config;
  const voiceID = selectedVoiceID();
  if (!voiceID) {
    renderInfo();
    setSynthesizeEnabled();
    return null;
  }

  const key = voiceKey(config, voiceID);
  if (state.voiceBytes.has(key)) {
    renderInfo();
    setSynthesizeEnabled();
    return state.voiceBytes.get(key);
  }

  setAction(`Downloading voice ${voiceID}...`);
  try {
    const bytes = await ensureVoiceDownloaded(config, voiceID, state.loadAbort?.signal);
    if (selectedVoiceKey() === key) {
      setAction(`Voice ${voiceID} ready.`);
    }
    return bytes;
  } catch (err) {
    if (err?.name !== "AbortError" && selectedVoiceKey() === key) {
      setAction(`Voice ${voiceID} failed: ${formatError(err)}`);
    }
    return null;
  }
}

// selectLanguage switches the page to config: it drops the previous model,
// downloads the new one and its tokenizer.json from Hugging Face and loads
// them into the kernel. A local checkpoint file (the gated kyutai/pocket-tts
// weights, which can clone voices) replaces the model download; the tokenizer
// still comes from the config. A later switch supersedes an earlier one, whose
// downloads are aborted and whose result is ignored.
async function selectLanguage(config, checkpointFile = null) {
  const lang = (state.catalog?.languages || []).find((l) => l.name === config);
  if (!lang) {
    setAction(`Unknown model config ${config}`);
    return;
  }

  state.loadSeq += 1;
  const seq = state.loadSeq;
  const isCurrent = () => seq === state.loadSeq;

  if (state.loadAbort) state.loadAbort.abort();
  const abort = new AbortController();
  state.loadAbort = abort;

  state.config = config;
  languageSelect.value = config;
  state.modelPhase = "downloading";
  state.modelError = "";
  state.checkpointName = checkpointFile ? checkpointFile.name : "";
  state.canClone = false;
  dropClonedVoices();
  resetRecording();
  applyLanguageDefaults(lang);
  renderInfo();
  setSynthesizeEnabled();

  void downloadSelectedVoiceIfNeeded();

  // Free the previous model before the new one arrives, also one a superseded
  // switch is still loading (the unload queues behind it).
  state.loadedConfig = "";
  void state.kernelReadyPromise
    .then(() => enqueueKernel(() => globalThis.PocketTTSKernel.unloadModel()))
    .catch(() => {});

  try {
    let modelPromise;
    if (checkpointFile) {
      showProgress(`Reading ${checkpointFile.name}...`, 0, false);
      setAction(`Reading local checkpoint ${checkpointFile.name} for ${config}...`);
      modelPromise = checkpointFile.arrayBuffer().then((buf) => new Uint8Array(buf));
    } else {
      showProgress(`Downloading ${config}...`, 0, false);
      setAction(`Downloading ${config} model...`);
      modelPromise = fetchBytesWithProgress(
        lang.model,
        (received, total) => {
          if (!isCurrent()) return;
          const pct = total > 0 ? Math.min(100, Math.round((received / total) * 100)) : 0;
          showProgress(`Downloading ${config}... ${pct}%`, pct, false);
          setAction(`Downloading ${config} model (${pct}%)...`);
        },
        abort.signal,
      );
    }

    const [modelBytes, tokenizerBytes] = await Promise.all([
      modelPromise,
      fetchBytesWithProgress(lang.tokenizer, null, abort.signal),
    ]);

    await state.kernelReadyPromise;

    const result = await enqueueKernel(async () => {
      if (!isCurrent()) return null;

      state.modelPhase = "initializing";
      showProgress(`Initializing ${config}...`, 0, false);
      setAction(`Initializing ${config}...`);

      return globalThis.PocketTTSKernel.loadModel(
        modelBytes,
        tokenizerBytes,
        (evt) => {
          if (!isCurrent()) return;
          const stage = evt?.stage || "load";
          const pct = Math.round(Math.max(0, Math.min(100, Number(evt?.percent || 0))));
          showProgress(`Initializing ${config} (${stage})... ${pct}%`, pct, false);
          setAction(`Initializing ${config} (${stage} ${pct}%)...`);
        },
        { config },
      );
    });

    if (!isCurrent()) return;
    if (!result?.ok) {
      throw new Error(result?.error || "model load failed");
    }

    state.loadedConfig = result.config || config;
    state.modelPhase = "ready";
    state.canClone = !!result.can_clone;
    showProgress(`${config} ready`, 100, true);
    setAction(`${config} ready (${modelSourceText()}).`);
    setTimeout(hideProgress, 2000);
  } catch (err) {
    // A stopped kernel has already said so; its calls fail with noise.
    if (!isCurrent() || state.kernelStopped) return;
    state.modelPhase = "error";
    state.modelError = formatError(err);
    hideProgress();
    setAction(`${config} failed: ${state.modelError}`);
  } finally {
    if (isCurrent()) {
      renderInfo();
      setSynthesizeEnabled();
    }
  }
}

// cloneVoiceFromWAV encodes a WAV prompt with the loaded checkpoint's voice
// encoder and adds the result as clone-<baseName> to the voice dropdown of the
// config it was cloned for, cached like a downloaded voice. wavBytes may also
// be a promise of the bytes (a file still being read). sourceLabel names the
// prompt in status messages. It reports whether the voice was cloned.
async function cloneVoiceFromWAV(wavBytes, sourceLabel, baseName) {
  const config = state.config;
  // A checkpoint switch while the clone runs drops cloned voices; the result
  // of this one would come from the previous checkpoint's encoder.
  const loadSeq = state.loadSeq;
  if (!modelReady() || !state.canClone) {
    renderInfo();
    return false;
  }

  const voiceID = `clone-${baseName}`;

  state.isCloning = true;
  setSynthesizeEnabled();
  setAction(`Cloning voice from ${sourceLabel}...`);

  try {
    const promptBytes = await wavBytes;
    const result = await enqueueKernel(() => {
      if (state.loadSeq !== loadSeq || state.loadedConfig !== config) {
        throw new Error(`the ${config} checkpoint is no longer loaded`);
      }
      return globalThis.PocketTTSKernel.cloneVoice(promptBytes);
    });
    if (!result?.ok) {
      throw new Error(result?.error || "voice cloning failed");
    }
    if (state.loadSeq !== loadSeq) {
      throw new Error("the checkpoint changed while cloning; clone the voice again");
    }

    state.voiceBytes.set(voiceKey(config, voiceID), result.voice_safetensors);
    state.voiceErrors.delete(voiceKey(config, voiceID));
    const ids = clonedVoiceIDs(config).filter((id) => id !== voiceID);
    state.clonedVoices.set(config, [...ids, voiceID]);

    if (state.config === config) {
      const lang = state.catalog.languages.find((l) => l.name === config);
      populateVoiceDropdown(lang);
      voiceSelect.value = voiceID;
    }
    setAction(`Cloned voice ${voiceID} from ${sourceLabel} (${result.frames} frames).`);
    return true;
  } catch (err) {
    setAction(`Voice cloning failed: ${formatError(err)}`);
    return false;
  } finally {
    state.isCloning = false;
    renderInfo();
    setSynthesizeEnabled();
  }
}

function cloneVoiceFromFile(file) {
  const base = file.name.replace(/\.[^.]*$/, "").trim() || "voice";
  // cloneVoiceFromWAV awaits the read, so a failed read fails the clone; the
  // empty catch only keeps a rejection its guards skip from going unhandled.
  const wavBytes = file.arrayBuffer().then((buf) => new Uint8Array(buf));
  wavBytes.catch(() => {});
  return cloneVoiceFromWAV(wavBytes, file.name, base);
}

// resetRecording closes the microphone panel: it stops a running capture,
// drops the last take and supersedes a pending start or stop.
function resetRecording() {
  state.recordSeq += 1;
  if (state.recorder) {
    state.recorder.cancel();
    state.recorder = null;
  }
  if (state.recording) {
    URL.revokeObjectURL(state.recording.url);
    state.recording = null;
  }
  state.recordPhase = "closed";
}

function openRecordPanel() {
  if (state.recordPhase === "closed") {
    state.recordPhase = "ready";
    recordScript.textContent = readingScript(state.config);
    setRecordMeter(0, 0);
  }
  renderRecordPanel();
  recordPanel.scrollIntoView({ behavior: "smooth", block: "nearest" });
}

// startTake asks for the microphone and starts a recording. The panel can
// close and the model can switch while the browser asks for permission; a
// recorder that arrives after that is cancelled.
async function startTake() {
  if (state.recordPhase !== "ready" || !modelReady() || !state.canClone) return;
  const seq = state.recordSeq + 1;
  state.recordSeq = seq;
  const isCurrent = () => seq === state.recordSeq;

  state.recordPhase = "starting";
  setRecordMeter(0, 0);
  setAction("Waiting for microphone permission...");
  setSynthesizeEnabled();

  let recorder;
  try {
    recorder = await startRecording({
      maxSeconds: recordMaxSeconds,
      onProgress: ({ seconds, level }) => {
        if (isCurrent()) setRecordMeter(seconds, level);
      },
      onLimit: () => {
        if (isCurrent()) void stopTake();
      },
    });
  } catch (err) {
    if (!isCurrent()) return;
    state.recordPhase = "ready";
    setAction(`Recording failed: ${formatError(err)}`);
    setSynthesizeEnabled();
    return;
  }

  if (!isCurrent()) {
    recorder.cancel();
    return;
  }
  state.recorder = recorder;
  state.recordPhase = "recording";
  setAction(`Recording at ${recorder.sampleRate} Hz...`);
  setSynthesizeEnabled();
}

async function stopTake() {
  const recorder = state.recorder;
  if (state.recordPhase !== "recording" || !recorder) return;
  const seq = state.recordSeq;
  const isCurrent = () => seq === state.recordSeq;

  state.recordPhase = "stopping";
  setSynthesizeEnabled();

  try {
    const { wav, seconds } = await recorder.stop();
    if (!isCurrent()) return;
    state.recorder = null;
    if (seconds <= 0) {
      throw new Error("no audio was captured");
    }

    const url = URL.createObjectURL(new Blob([wav], { type: "audio/wav" }));
    state.recording = { wav, url, seconds };
    state.recordPhase = "recorded";
    if (seconds < recordShortSeconds) {
      setAction(`Short recording (${seconds.toFixed(1)} s); 10 s or more clone better.`);
    } else {
      setAction(`Recorded ${seconds.toFixed(1)} s.`);
    }
  } catch (err) {
    if (!isCurrent()) return;
    state.recorder = null;
    state.recordPhase = "ready";
    setAction(`Recording failed: ${formatError(err)}`);
  } finally {
    if (isCurrent()) setSynthesizeEnabled();
  }
}

function retakeRecording() {
  if (state.recordPhase !== "recorded") return;
  if (state.recording) {
    URL.revokeObjectURL(state.recording.url);
    state.recording = null;
  }
  state.recordPhase = "ready";
  void startTake();
}

function discardRecording() {
  const discarded = state.recordPhase !== "ready" && state.recordPhase !== "closed";
  resetRecording();
  if (discarded) {
    setAction("Recording discarded.");
  }
  setSynthesizeEnabled();
}

// cloneRecording clones the last take. A failed clone keeps it for a retry.
async function cloneRecording() {
  const recording = state.recording;
  if (state.recordPhase !== "recorded" || !recording || state.isCloning) return;

  const n = state.recordingCount + 1;
  const ok = await cloneVoiceFromWAV(recording.wav, "your recording", `recording-${n}`);
  if (!ok) return;

  state.recordingCount = n;
  if (state.recording === recording) {
    resetRecording();
    setSynthesizeEnabled();
  }
}

function rAF() {
  return new Promise((resolve) => requestAnimationFrame(resolve));
}

async function runSynthesis(text) {
  try {
    const options = { temperature: parseFloat(temperatureSlider.value) };
    const voiceSafetensors = await downloadSelectedVoiceIfNeeded();
    if (voiceSafetensors) {
      options.voiceSafetensors = voiceSafetensors;
    }

    const t0 = performance.now();
    const result = await globalThis.PocketTTSKernel.synthesize(
      text,
      (evt) => {
        const pct = Math.round(Math.max(0, Math.min(100, Number(evt?.percent || 0))));
        const stage = evt?.stage || "working";
        const detail = evt?.detail || stage;
        showProgress(`Synthesizing... ${pct}%`, pct, false);
        setAction(`Synthesizing — ${detail} (${pct}%)`);
      },
      options,
    );
    const elapsedMs = (performance.now() - t0).toFixed(1);

    if (!result?.ok) {
      throw new Error(result?.error || "synthesis failed");
    }

    const wavBytes = decodeBase64ToBytes(result.wav_base64 || "");
    setAudioBlob(wavBytes);
    showProgress(`Done in ${elapsedMs} ms`, 100, true);
    setAction(`Synthesis complete in ${elapsedMs} ms.`);
    setTimeout(hideProgress, 3000);
  } catch (err) {
    hideProgress();
    setAction(`Synthesis failed: ${formatError(err)}`);
  } finally {
    state.isSynthesizing = false;
    renderInfo();
    setSynthesizeEnabled();
  }
}

function handleSynthesize() {
  if (synthBtn.disabled || state.isSynthesizing) {
    return;
  }

  state.isSynthesizing = true;
  state.textDirty = false;
  setSynthesizeEnabled();
  showProgress("Synthesizing...", 0, false);
  setAction("Synthesizing...");

  // Capture text now; user may freely edit while synthesis runs.
  const text = textArea.value;

  // Yield to the browser so the UI repaints before the heavy WASM call.
  rAF().then(() => runSynthesis(text));
}

async function loadCatalog() {
  const res = await fetch(catalogAssetPath);
  if (!res.ok) {
    throw new Error(`fetch ${catalogAssetPath} failed (${res.status})`);
  }

  const catalog = await res.json();
  if (!catalog?.languages?.length) {
    throw new Error(`${catalogAssetPath} lists no model configs`);
  }

  state.catalog = catalog;
  populateLanguageDropdown();
}

async function initApp() {
  renderInfo();
  setSynthesizeEnabled();

  // Boot the kernel while the model downloads.
  state.kernelReadyPromise = bootKernel();
  state.kernelReadyPromise.catch((err) => {
    setAction(`Kernel startup failed: ${formatError(err)}`);
    setSynthesizeEnabled();
  });

  try {
    await loadCatalog();
  } catch (err) {
    setAction(`Model list unavailable: ${formatError(err)}`);
    return;
  }

  await selectLanguage(state.catalog.default || state.catalog.languages[0].name);
}

synthBtn.addEventListener("click", () => handleSynthesize());
textArea.addEventListener("input", () => {
  state.textEdited = true;
  if (state.isSynthesizing && !state.textDirty) {
    state.textDirty = true;
    setSynthesizeEnabled();
  }
});
languageSelect.addEventListener("change", () => {
  // A picked checkpoint belongs to the config it was picked for.
  checkpointInput.value = "";
  void selectLanguage(languageSelect.value);
});
checkpointInput.addEventListener("change", () => {
  const file = checkpointInput.files?.[0];
  if (file) void selectLanguage(state.config, file);
});
cloneInput.addEventListener("change", () => {
  const file = cloneInput.files?.[0];
  cloneInput.value = "";
  if (file) void cloneVoiceFromFile(file);
});
recordBtn.addEventListener("click", () => openRecordPanel());
recordStartBtn.addEventListener("click", () => void startTake());
recordStopBtn.addEventListener("click", () => void stopTake());
recordRetakeBtn.addEventListener("click", () => retakeRecording());
recordDiscardBtn.addEventListener("click", () => discardRecording());
recordCloneBtn.addEventListener("click", () => void cloneRecording());
voiceSelect.addEventListener("change", () => {
  renderInfo();
  setSynthesizeEnabled();
  void downloadSelectedVoiceIfNeeded();
});
temperatureSlider.addEventListener("input", () => {
  setTemperature(parseFloat(temperatureSlider.value));
});

initApp().catch((err) => {
  setAction(`Startup failed: ${formatError(err)}`);
});
